services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    command: run_app
    networks:
      - app-network

  db:
    image: postgres:17.3
    container_name: db
    environment:
      POSTGRES_USER: ${MAIN_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${MAIN_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${MAIN_DB_PASSWORD:-app_db}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
     - app-network

volumes:
    db-data:

networks:
    app-network:
        driver: bridge
